import { Product, HeroSlide, Testimonial, BlogPost, Collection, FAQItem, Stat } from '@/types'

// Pet images from Unsplash
const petImages = {
  dogs: [
    'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
    'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800',
    'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=800',
    'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800',
    'https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=800',
  ],
  cats: [
    'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800',
    'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=800',
    'https://images.unsplash.com/photo-1495360010541-f48722b34f7d?w=800',
    'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=800',
  ],
  products: [
    'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800',
    'https://images.unsplash.com/photo-1535294435445-d7249524ef2e?w=800',
    'https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=800',
  ],
}

// Helper to generate reviews (Indian names)
const generateReviews = (count: number) => {
  const names = ['Priya S.', 'Rahul M.', 'Ananya K.', 'Vikram R.', 'Neha P.', 'Arjun D.', 'Kavya G.', 'Aditya T.', 'Sneha B.', 'Rohan V.']
  const titles = ['Bahut accha product!', 'My pet loves it!', 'Excellent quality', 'Highly recommend', 'Best purchase ever!', 'Worth every rupee!']
  const contents = [
    'This product exceeded my expectations. My furry friend absolutely loves it!',
    'Mera Tommy is product ko bahut pasand karta hai! Fast delivery bhi mili.',
    'Amazing quality at this price. Will definitely buy again from BowPaw.',
    'Best pet store in India! My dog is so happy with this purchase.',
    'Superb product, exactly as described. My cat cannot stop playing with it!',
  ]
  const reviews = []
  for (let i = 0; i < count; i++) {
    reviews.push({
      id: `review-${i}`,
      author: names[i % names.length],
      rating: 4 + Math.random(),
      title: titles[i % titles.length],
      content: contents[i % contents.length],
      date: new Date(Date.now() - i * 86400000 * 3).toISOString(),
      verified: Math.random() > 0.3,
      helpful: Math.floor(Math.random() * 50),
    })
  }
  return reviews
}

// Products data - 50 products
export const products: Product[] = [
  // Dog Food Category (1-10)
  {
    id: '1',
    name: 'Premium Grain-Free Dog Food',
    slug: 'premium-grain-free-dog-food',
    description: 'Our premium grain-free formula is crafted with real chicken as the first ingredient, providing high-quality protein for strong muscles. Enriched with sweet potatoes and peas for healthy digestion, plus omega fatty acids for a shiny coat.',
    shortDescription: 'High-protein grain-free formula with real chicken',
    price: 54.99,
    compareAtPrice: 69.99,
    category: 'Dog Food',
    subcategory: 'Dry Food',
    tags: ['grain-free', 'chicken', 'premium', 'adult-dog'],
    images: [petImages.products[0], petImages.products[1], petImages.products[2]],
    variants: [
      { id: 'v1-1', name: '5 lb Bag', price: 24.99, stock: 50 },
      { id: 'v1-2', name: '15 lb Bag', price: 54.99, stock: 30 },
      { id: 'v1-3', name: '30 lb Bag', price: 89.99, stock: 20 },
    ],
    reviews: generateReviews(5),
    rating: 4.8,
    reviewCount: 245,
    stock: 100,
    sku: 'DF-001',
    brand: 'BowPaw Naturals',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'dog',
    createdAt: '2024-01-15',
    specifications: { Weight: '15 lb', 'Life Stage': 'Adult', Flavor: 'Chicken' },
  },
  {
    id: '2',
    name: 'Puppy Growth Formula',
    slug: 'puppy-growth-formula',
    description: 'Specially formulated for growing puppies with DHA for brain development and calcium for strong bones.',
    shortDescription: 'Complete nutrition for growing puppies',
    price: 45.99,
    compareAtPrice: 55.99,
    category: 'Dog Food',
    subcategory: 'Dry Food',
    tags: ['puppy', 'growth', 'dha', 'calcium'],
    images: [petImages.products[1], petImages.products[0]],
    variants: [
      { id: 'v2-1', name: '5 lb Bag', price: 22.99, stock: 40 },
      { id: 'v2-2', name: '15 lb Bag', price: 45.99, stock: 25 },
    ],
    reviews: generateReviews(4),
    rating: 4.9,
    reviewCount: 189,
    stock: 65,
    sku: 'DF-002',
    brand: 'BowPaw Naturals',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: true,
    petType: 'dog',
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    name: 'Senior Dog Wellness Blend',
    slug: 'senior-dog-wellness-blend',
    description: 'Gentle formula for senior dogs with glucosamine for joint health and easy-to-digest ingredients.',
    shortDescription: 'Joint-supporting formula for senior dogs',
    price: 58.99,
    category: 'Dog Food',
    subcategory: 'Dry Food',
    tags: ['senior', 'joint-health', 'glucosamine'],
    images: [petImages.products[2], petImages.products[1]],
    variants: [
      { id: 'v3-1', name: '12 lb Bag', price: 58.99, stock: 35 },
      { id: 'v3-2', name: '24 lb Bag', price: 99.99, stock: 20 },
    ],
    reviews: generateReviews(3),
    rating: 4.7,
    reviewCount: 156,
    stock: 55,
    sku: 'DF-003',
    brand: 'BowPaw Naturals',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    name: 'Wild Salmon & Sweet Potato',
    slug: 'wild-salmon-sweet-potato',
    description: 'Premium wild-caught salmon recipe rich in omega-3 fatty acids for healthy skin and coat.',
    shortDescription: 'Omega-rich salmon formula',
    price: 62.99,
    compareAtPrice: 74.99,
    category: 'Dog Food',
    subcategory: 'Dry Food',
    tags: ['salmon', 'omega-3', 'skin-coat'],
    images: [petImages.products[0], petImages.products[2]],
    variants: [
      { id: 'v4-1', name: '13 lb Bag', price: 62.99, stock: 28 },
    ],
    reviews: generateReviews(6),
    rating: 4.9,
    reviewCount: 312,
    stock: 28,
    sku: 'DF-004',
    brand: 'Ocean Paws',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'dog',
    createdAt: '2023-12-10',
  },
  {
    id: '5',
    name: 'Organic Beef & Vegetable Stew',
    slug: 'organic-beef-vegetable-stew',
    description: 'Human-grade organic beef with garden vegetables in savory gravy. Perfect for picky eaters.',
    shortDescription: 'Premium wet food with organic beef',
    price: 4.99,
    category: 'Dog Food',
    subcategory: 'Wet Food',
    tags: ['organic', 'beef', 'wet-food', 'premium'],
    images: [petImages.products[1]],
    variants: [
      { id: 'v5-1', name: 'Single Can', price: 4.99, stock: 200 },
      { id: 'v5-2', name: '12-Pack', price: 49.99, stock: 50 },
      { id: 'v5-3', name: '24-Pack', price: 89.99, stock: 25 },
    ],
    reviews: generateReviews(4),
    rating: 4.6,
    reviewCount: 178,
    stock: 275,
    sku: 'DF-005',
    brand: 'Farm Fresh Pets',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2024-02-15',
  },
  // Dog Toys (6-15)
  {
    id: '6',
    name: 'Indestructible Chew Bone',
    slug: 'indestructible-chew-bone',
    description: 'Ultra-durable nylon bone designed for aggressive chewers. Bacon-flavored for irresistible appeal.',
    shortDescription: 'Virtually indestructible chew toy',
    price: 18.99,
    compareAtPrice: 24.99,
    category: 'Dog Toys',
    subcategory: 'Chew Toys',
    tags: ['durable', 'chew', 'bacon-flavor'],
    images: [petImages.products[2], petImages.products[0]],
    variants: [
      { id: 'v6-1', name: 'Small', price: 14.99, stock: 60, size: 'S' },
      { id: 'v6-2', name: 'Medium', price: 18.99, stock: 45, size: 'M' },
      { id: 'v6-3', name: 'Large', price: 24.99, stock: 30, size: 'L' },
    ],
    reviews: generateReviews(7),
    rating: 4.5,
    reviewCount: 423,
    stock: 135,
    sku: 'DT-001',
    brand: 'ToughPup',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'dog',
    createdAt: '2023-11-20',
  },
  {
    id: '7',
    name: 'Interactive Puzzle Feeder',
    slug: 'interactive-puzzle-feeder',
    description: 'Stimulate your dogs mind with this challenging puzzle toy. Multiple difficulty levels.',
    shortDescription: 'Mental stimulation puzzle toy',
    price: 29.99,
    category: 'Dog Toys',
    subcategory: 'Puzzle Toys',
    tags: ['puzzle', 'interactive', 'mental-stimulation'],
    images: [petImages.products[1]],
    variants: [],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 287,
    stock: 45,
    sku: 'DT-002',
    brand: 'SmartPaws',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2024-01-25',
  },
  {
    id: '8',
    name: 'Squeaky Plush Collection',
    slug: 'squeaky-plush-collection',
    description: 'Set of 6 adorable plush toys with squeakers. Perfect for fetch and cuddle time.',
    shortDescription: '6-piece plush toy set',
    price: 24.99,
    compareAtPrice: 34.99,
    category: 'Dog Toys',
    subcategory: 'Plush Toys',
    tags: ['plush', 'squeaky', 'set', 'soft'],
    images: [petImages.products[0]],
    variants: [],
    reviews: generateReviews(8),
    rating: 4.4,
    reviewCount: 356,
    stock: 80,
    sku: 'DT-003',
    brand: 'Cuddle Pups',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'dog',
    createdAt: '2023-10-15',
  },
  {
    id: '9',
    name: 'Rubber Fetch Ball Set',
    slug: 'rubber-fetch-ball-set',
    description: 'High-bounce rubber balls in vibrant colors. Floats in water for pool play.',
    shortDescription: 'Durable rubber balls for fetch',
    price: 12.99,
    category: 'Dog Toys',
    subcategory: 'Fetch Toys',
    tags: ['ball', 'fetch', 'outdoor', 'water-safe'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v9-1', name: '3-Pack', price: 12.99, stock: 100 },
      { id: 'v9-2', name: '6-Pack', price: 21.99, stock: 60 },
    ],
    reviews: generateReviews(4),
    rating: 4.6,
    reviewCount: 198,
    stock: 160,
    sku: 'DT-004',
    brand: 'PlayTime',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2023-09-01',
  },
  {
    id: '10',
    name: 'Tug-of-War Rope Toy',
    slug: 'tug-of-war-rope-toy',
    description: 'Heavy-duty cotton rope toy for interactive play. Cleans teeth while playing.',
    shortDescription: 'Durable rope for tug games',
    price: 14.99,
    category: 'Dog Toys',
    subcategory: 'Rope Toys',
    tags: ['rope', 'tug', 'dental', 'interactive'],
    images: [petImages.products[1]],
    variants: [
      { id: 'v10-1', name: 'Medium', price: 14.99, stock: 75, size: 'M' },
      { id: 'v10-2', name: 'Large', price: 19.99, stock: 50, size: 'L' },
      { id: 'v10-3', name: 'XL', price: 24.99, stock: 30, size: 'XL' },
    ],
    reviews: generateReviews(5),
    rating: 4.5,
    reviewCount: 267,
    stock: 155,
    sku: 'DT-005',
    brand: 'ToughPup',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2023-08-15',
  },
  // Dog Beds & Accessories (11-20)
  {
    id: '11',
    name: 'Orthopedic Memory Foam Bed',
    slug: 'orthopedic-memory-foam-bed',
    description: 'Premium memory foam bed with removable, washable cover. Perfect for senior dogs or those with joint issues.',
    shortDescription: 'Supportive memory foam dog bed',
    price: 89.99,
    compareAtPrice: 119.99,
    category: 'Dog Beds',
    subcategory: 'Orthopedic',
    tags: ['orthopedic', 'memory-foam', 'senior', 'washable'],
    images: [petImages.products[0], petImages.products[1]],
    variants: [
      { id: 'v11-1', name: 'Medium (30x20")', price: 89.99, stock: 25, size: 'M' },
      { id: 'v11-2', name: 'Large (40x30")', price: 119.99, stock: 20, size: 'L' },
      { id: 'v11-3', name: 'XL (50x35")', price: 149.99, stock: 15, size: 'XL' },
    ],
    reviews: generateReviews(6),
    rating: 4.9,
    reviewCount: 445,
    stock: 60,
    sku: 'DB-001',
    brand: 'ComfortPaws',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'dog',
    createdAt: '2023-07-20',
  },
  {
    id: '12',
    name: 'Cozy Donut Cuddler Bed',
    slug: 'cozy-donut-cuddler-bed',
    description: 'Round bolster bed with raised edges for dogs who love to curl up. Ultra-soft faux fur.',
    shortDescription: 'Plush donut-shaped bed',
    price: 49.99,
    category: 'Dog Beds',
    subcategory: 'Bolster',
    tags: ['donut', 'cozy', 'faux-fur', 'bolster'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v12-1', name: 'Small', price: 39.99, stock: 40, size: 'S', color: 'Gray' },
      { id: 'v12-2', name: 'Medium', price: 49.99, stock: 35, size: 'M', color: 'Gray' },
      { id: 'v12-3', name: 'Large', price: 64.99, stock: 25, size: 'L', color: 'Gray' },
    ],
    reviews: generateReviews(4),
    rating: 4.7,
    reviewCount: 312,
    stock: 100,
    sku: 'DB-002',
    brand: 'SnugglePups',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2024-02-10',
  },
  {
    id: '13',
    name: 'Elevated Cooling Dog Bed',
    slug: 'elevated-cooling-dog-bed',
    description: 'Breathable mesh design keeps dogs cool in summer. Raised design prevents joint pressure.',
    shortDescription: 'Elevated mesh cooling bed',
    price: 44.99,
    category: 'Dog Beds',
    subcategory: 'Elevated',
    tags: ['cooling', 'elevated', 'mesh', 'summer'],
    images: [petImages.products[1]],
    variants: [
      { id: 'v13-1', name: 'Medium', price: 44.99, stock: 30, size: 'M' },
      { id: 'v13-2', name: 'Large', price: 59.99, stock: 25, size: 'L' },
    ],
    reviews: generateReviews(5),
    rating: 4.6,
    reviewCount: 223,
    stock: 55,
    sku: 'DB-003',
    brand: 'CoolPups',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2023-06-15',
  },
  {
    id: '14',
    name: 'Adjustable Dog Harness',
    slug: 'adjustable-dog-harness',
    description: 'No-pull harness with reflective stitching for safety. Padded chest plate for comfort.',
    shortDescription: 'Comfortable no-pull harness',
    price: 34.99,
    compareAtPrice: 44.99,
    category: 'Dog Accessories',
    subcategory: 'Harnesses',
    tags: ['harness', 'no-pull', 'reflective', 'adjustable'],
    images: [petImages.products[0]],
    variants: [
      { id: 'v14-1', name: 'XS', price: 29.99, stock: 30, size: 'XS', color: 'Black' },
      { id: 'v14-2', name: 'S', price: 32.99, stock: 40, size: 'S', color: 'Black' },
      { id: 'v14-3', name: 'M', price: 34.99, stock: 50, size: 'M', color: 'Black' },
      { id: 'v14-4', name: 'L', price: 37.99, stock: 35, size: 'L', color: 'Black' },
      { id: 'v14-5', name: 'XL', price: 39.99, stock: 25, size: 'XL', color: 'Black' },
    ],
    reviews: generateReviews(7),
    rating: 4.8,
    reviewCount: 567,
    stock: 180,
    sku: 'DA-001',
    brand: 'WalkSafe',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'dog',
    createdAt: '2023-05-10',
  },
  {
    id: '15',
    name: 'Retractable Dog Leash',
    slug: 'retractable-dog-leash',
    description: '16ft retractable leash with comfortable grip and one-button lock system.',
    shortDescription: 'Extendable walk leash',
    price: 24.99,
    category: 'Dog Accessories',
    subcategory: 'Leashes',
    tags: ['leash', 'retractable', 'walking', '16ft'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v15-1', name: 'Small (up to 25 lbs)', price: 19.99, stock: 45, size: 'S' },
      { id: 'v15-2', name: 'Medium (up to 55 lbs)', price: 24.99, stock: 50, size: 'M' },
      { id: 'v15-3', name: 'Large (up to 110 lbs)', price: 29.99, stock: 40, size: 'L' },
    ],
    reviews: generateReviews(4),
    rating: 4.4,
    reviewCount: 289,
    stock: 135,
    sku: 'DA-002',
    brand: 'WalkSafe',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2023-04-20',
  },
  // Cat Products (16-30)
  {
    id: '16',
    name: 'Premium Indoor Cat Food',
    slug: 'premium-indoor-cat-food',
    description: 'Specially formulated for indoor cats with hairball control and weight management.',
    shortDescription: 'Indoor formula with hairball control',
    price: 39.99,
    compareAtPrice: 49.99,
    category: 'Cat Food',
    subcategory: 'Dry Food',
    tags: ['indoor', 'hairball', 'weight-control'],
    images: [petImages.products[1]],
    variants: [
      { id: 'v16-1', name: '3.5 lb Bag', price: 19.99, stock: 60 },
      { id: 'v16-2', name: '7 lb Bag', price: 39.99, stock: 40 },
      { id: 'v16-3', name: '14 lb Bag', price: 69.99, stock: 25 },
    ],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 334,
    stock: 125,
    sku: 'CF-001',
    brand: 'PurrfectMeals',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'cat',
    createdAt: '2023-11-01',
  },
  {
    id: '17',
    name: 'Kitten Growth Formula',
    slug: 'kitten-growth-formula',
    description: 'Nutrient-rich formula for growing kittens with DHA for brain and vision development.',
    shortDescription: 'Complete kitten nutrition',
    price: 34.99,
    category: 'Cat Food',
    subcategory: 'Dry Food',
    tags: ['kitten', 'growth', 'dha'],
    images: [petImages.products[0]],
    variants: [
      { id: 'v17-1', name: '3 lb Bag', price: 18.99, stock: 50 },
      { id: 'v17-2', name: '6 lb Bag', price: 34.99, stock: 35 },
    ],
    reviews: generateReviews(4),
    rating: 4.8,
    reviewCount: 198,
    stock: 85,
    sku: 'CF-002',
    brand: 'PurrfectMeals',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'cat',
    createdAt: '2024-01-30',
  },
  {
    id: '18',
    name: 'Gourmet Pate Variety Pack',
    slug: 'gourmet-pate-variety-pack',
    description: 'Premium pate in 4 flavors: Chicken, Salmon, Turkey, and Ocean Fish.',
    shortDescription: '24-can gourmet variety pack',
    price: 36.99,
    compareAtPrice: 45.99,
    category: 'Cat Food',
    subcategory: 'Wet Food',
    tags: ['pate', 'variety', 'gourmet', 'wet-food'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v18-1', name: '12-Pack', price: 21.99, stock: 40 },
      { id: 'v18-2', name: '24-Pack', price: 36.99, stock: 30 },
    ],
    reviews: generateReviews(6),
    rating: 4.6,
    reviewCount: 412,
    stock: 70,
    sku: 'CF-003',
    brand: 'Whisker Delights',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'cat',
    createdAt: '2023-09-15',
  },
  {
    id: '19',
    name: 'Interactive Feather Wand',
    slug: 'interactive-feather-wand',
    description: 'Extendable wand toy with natural feathers to stimulate hunting instincts.',
    shortDescription: 'Interactive hunting toy',
    price: 14.99,
    category: 'Cat Toys',
    subcategory: 'Interactive',
    tags: ['feather', 'wand', 'interactive', 'hunting'],
    images: [petImages.products[1]],
    variants: [],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 523,
    stock: 150,
    sku: 'CT-001',
    brand: 'PlayCat',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'cat',
    createdAt: '2023-08-01',
  },
  {
    id: '20',
    name: 'Automatic Laser Pointer',
    slug: 'automatic-laser-pointer',
    description: 'Battery-operated laser toy with random patterns to keep cats entertained for hours.',
    shortDescription: 'Self-playing laser toy',
    price: 24.99,
    category: 'Cat Toys',
    subcategory: 'Electronic',
    tags: ['laser', 'automatic', 'electronic', 'interactive'],
    images: [petImages.products[0]],
    variants: [],
    reviews: generateReviews(4),
    rating: 4.5,
    reviewCount: 287,
    stock: 60,
    sku: 'CT-002',
    brand: 'TechPet',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'cat',
    createdAt: '2024-02-05',
  },
  {
    id: '21',
    name: 'Catnip Mouse Set',
    slug: 'catnip-mouse-set',
    description: 'Pack of 12 realistic mice filled with organic catnip.',
    shortDescription: '12-pack catnip mice',
    price: 9.99,
    category: 'Cat Toys',
    subcategory: 'Catnip Toys',
    tags: ['catnip', 'mouse', 'organic', 'set'],
    images: [petImages.products[2]],
    variants: [],
    reviews: generateReviews(7),
    rating: 4.6,
    reviewCount: 678,
    stock: 200,
    sku: 'CT-003',
    brand: 'NipTime',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'cat',
    createdAt: '2023-06-10',
  },
  {
    id: '22',
    name: 'Multi-Level Cat Tree',
    slug: 'multi-level-cat-tree',
    description: '6-tier cat tower with scratching posts, hammock, and enclosed condo.',
    shortDescription: 'Large cat tower playground',
    price: 129.99,
    compareAtPrice: 169.99,
    category: 'Cat Furniture',
    subcategory: 'Cat Trees',
    tags: ['cat-tree', 'scratching', 'condo', 'large'],
    images: [petImages.products[1]],
    variants: [
      { id: 'v22-1', name: 'Beige', price: 129.99, stock: 15, color: 'Beige' },
      { id: 'v22-2', name: 'Gray', price: 129.99, stock: 12, color: 'Gray' },
      { id: 'v22-3', name: 'Brown', price: 129.99, stock: 10, color: 'Brown' },
    ],
    reviews: generateReviews(5),
    rating: 4.8,
    reviewCount: 234,
    stock: 37,
    sku: 'CC-001',
    brand: 'CatCastle',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'cat',
    createdAt: '2023-10-20',
  },
  {
    id: '23',
    name: 'Wall-Mounted Cat Shelves',
    slug: 'wall-mounted-cat-shelves',
    description: 'Set of 3 floating shelves with sisal scratching surfaces. Space-saving design.',
    shortDescription: '3-piece wall shelf set',
    price: 69.99,
    category: 'Cat Furniture',
    subcategory: 'Shelves',
    tags: ['wall-mount', 'shelves', 'scratching', 'modern'],
    images: [petImages.products[0]],
    variants: [
      { id: 'v23-1', name: 'White', price: 69.99, stock: 20, color: 'White' },
      { id: 'v23-2', name: 'Walnut', price: 69.99, stock: 18, color: 'Walnut' },
    ],
    reviews: generateReviews(4),
    rating: 4.7,
    reviewCount: 156,
    stock: 38,
    sku: 'CC-002',
    brand: 'ModernCat',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'cat',
    createdAt: '2024-01-15',
  },
  {
    id: '24',
    name: 'Self-Cleaning Litter Box',
    slug: 'self-cleaning-litter-box',
    description: 'Automatic rake system sifts waste into sealed compartment. Low odor guarantee.',
    shortDescription: 'Automatic litter box',
    price: 179.99,
    compareAtPrice: 229.99,
    category: 'Cat Litter',
    subcategory: 'Litter Boxes',
    tags: ['self-cleaning', 'automatic', 'low-odor'],
    images: [petImages.products[2]],
    variants: [],
    reviews: generateReviews(6),
    rating: 4.4,
    reviewCount: 345,
    stock: 25,
    sku: 'CL-001',
    brand: 'CleanPaws',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: true,
    petType: 'cat',
    createdAt: '2023-07-01',
  },
  {
    id: '25',
    name: 'Premium Clumping Litter',
    slug: 'premium-clumping-litter',
    description: 'Ultra-absorbent bentonite clay litter with 7-day odor control.',
    shortDescription: 'Fast-clumping odor control litter',
    price: 19.99,
    category: 'Cat Litter',
    subcategory: 'Clumping',
    tags: ['clumping', 'odor-control', 'bentonite'],
    images: [petImages.products[1]],
    variants: [
      { id: 'v25-1', name: '14 lb Box', price: 19.99, stock: 80 },
      { id: 'v25-2', name: '28 lb Box', price: 34.99, stock: 50 },
      { id: 'v25-3', name: '40 lb Box', price: 44.99, stock: 30 },
    ],
    reviews: generateReviews(5),
    rating: 4.6,
    reviewCount: 567,
    stock: 160,
    sku: 'CL-002',
    brand: 'FreshScent',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'cat',
    createdAt: '2023-05-15',
  },
  // Small Pets (26-35)
  {
    id: '26',
    name: 'Hamster Starter Kit',
    slug: 'hamster-starter-kit',
    description: 'Complete setup with cage, wheel, water bottle, and food dish.',
    shortDescription: 'Everything for new hamster owners',
    price: 49.99,
    compareAtPrice: 64.99,
    category: 'Small Pet Supplies',
    subcategory: 'Habitats',
    tags: ['hamster', 'starter-kit', 'cage', 'complete'],
    images: [petImages.products[0]],
    variants: [],
    reviews: generateReviews(4),
    rating: 4.5,
    reviewCount: 189,
    stock: 30,
    sku: 'SP-001',
    brand: 'SmallPetWorld',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: true,
    petType: 'small-pet',
    createdAt: '2024-02-01',
  },
  {
    id: '27',
    name: 'Guinea Pig Hay Blend',
    slug: 'guinea-pig-hay-blend',
    description: 'Premium timothy hay mixed with orchard grass and botanicals.',
    shortDescription: 'Nutritious hay for guinea pigs',
    price: 14.99,
    category: 'Small Pet Supplies',
    subcategory: 'Food',
    tags: ['guinea-pig', 'hay', 'timothy', 'organic'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v27-1', name: '24 oz', price: 14.99, stock: 60 },
      { id: 'v27-2', name: '48 oz', price: 24.99, stock: 40 },
    ],
    reviews: generateReviews(5),
    rating: 4.8,
    reviewCount: 234,
    stock: 100,
    sku: 'SP-002',
    brand: 'HayDays',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'small-pet',
    createdAt: '2023-12-10',
  },
  {
    id: '28',
    name: 'Rabbit Tunnel Play Set',
    slug: 'rabbit-tunnel-play-set',
    description: 'Collapsible tunnel system with multiple exits for exploration.',
    shortDescription: 'Expandable play tunnel',
    price: 29.99,
    category: 'Small Pet Supplies',
    subcategory: 'Toys',
    tags: ['rabbit', 'tunnel', 'play', 'collapsible'],
    images: [petImages.products[1]],
    variants: [],
    reviews: generateReviews(3),
    rating: 4.6,
    reviewCount: 145,
    stock: 45,
    sku: 'SP-003',
    brand: 'BunnyFun',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'small-pet',
    createdAt: '2023-11-15',
  },
  // Bird Products (29-35)
  {
    id: '29',
    name: 'Parakeet Seed Mix',
    slug: 'parakeet-seed-mix',
    description: 'Nutrient-rich seed blend with millet, canary grass, and added vitamins.',
    shortDescription: 'Premium parakeet food',
    price: 12.99,
    category: 'Bird Supplies',
    subcategory: 'Food',
    tags: ['parakeet', 'seed', 'vitamins'],
    images: [petImages.products[0]],
    variants: [
      { id: 'v29-1', name: '2 lb Bag', price: 12.99, stock: 70 },
      { id: 'v29-2', name: '5 lb Bag', price: 24.99, stock: 45 },
    ],
    reviews: generateReviews(4),
    rating: 4.5,
    reviewCount: 167,
    stock: 115,
    sku: 'BS-001',
    brand: 'FeatherFeast',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'bird',
    createdAt: '2023-10-01',
  },
  {
    id: '30',
    name: 'Large Flight Cage',
    slug: 'large-flight-cage',
    description: 'Spacious cage with multiple perches and feeding stations. Easy-clean bottom tray.',
    shortDescription: 'Deluxe bird flight cage',
    price: 149.99,
    compareAtPrice: 189.99,
    category: 'Bird Supplies',
    subcategory: 'Cages',
    tags: ['cage', 'large', 'flight', 'premium'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v30-1', name: 'White', price: 149.99, stock: 12, color: 'White' },
      { id: 'v30-2', name: 'Black', price: 149.99, stock: 10, color: 'Black' },
    ],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 198,
    stock: 22,
    sku: 'BS-002',
    brand: 'BirdPalace',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: true,
    petType: 'bird',
    createdAt: '2023-08-20',
  },
  // Fish Products (31-35)
  {
    id: '31',
    name: 'Tropical Fish Flakes',
    slug: 'tropical-fish-flakes',
    description: 'Color-enhancing formula with spirulina and essential nutrients.',
    shortDescription: 'Premium tropical fish food',
    price: 8.99,
    category: 'Fish Supplies',
    subcategory: 'Food',
    tags: ['tropical', 'flakes', 'color-enhancing'],
    images: [petImages.products[1]],
    variants: [
      { id: 'v31-1', name: '1 oz', price: 8.99, stock: 100 },
      { id: 'v31-2', name: '3.5 oz', price: 16.99, stock: 60 },
    ],
    reviews: generateReviews(5),
    rating: 4.6,
    reviewCount: 289,
    stock: 160,
    sku: 'FS-001',
    brand: 'AquaLife',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'fish',
    createdAt: '2023-09-05',
  },
  {
    id: '32',
    name: '10-Gallon Aquarium Kit',
    slug: '10-gallon-aquarium-kit',
    description: 'Complete setup with LED lighting, filter, heater, and thermometer.',
    shortDescription: 'Starter aquarium kit',
    price: 79.99,
    compareAtPrice: 99.99,
    category: 'Fish Supplies',
    subcategory: 'Aquariums',
    tags: ['aquarium', 'starter', 'led', 'complete'],
    images: [petImages.products[0]],
    variants: [],
    reviews: generateReviews(4),
    rating: 4.5,
    reviewCount: 234,
    stock: 25,
    sku: 'FS-002',
    brand: 'AquaLife',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: true,
    petType: 'fish',
    createdAt: '2024-01-20',
  },
  // Grooming Products (33-40)
  {
    id: '33',
    name: 'Deshedding Brush',
    slug: 'deshedding-brush',
    description: 'Stainless steel blade removes loose undercoat without damaging topcoat.',
    shortDescription: 'Professional deshedding tool',
    price: 29.99,
    category: 'Grooming',
    subcategory: 'Brushes',
    tags: ['deshedding', 'brush', 'undercoat'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v33-1', name: 'Small', price: 24.99, stock: 40, size: 'S' },
      { id: 'v33-2', name: 'Medium', price: 29.99, stock: 50, size: 'M' },
      { id: 'v33-3', name: 'Large', price: 34.99, stock: 35, size: 'L' },
    ],
    reviews: generateReviews(6),
    rating: 4.8,
    reviewCount: 567,
    stock: 125,
    sku: 'GR-001',
    brand: 'FurPerfect',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'all',
    createdAt: '2023-07-15',
  },
  {
    id: '34',
    name: 'Oatmeal Shampoo',
    slug: 'oatmeal-shampoo',
    description: 'Gentle formula with colloidal oatmeal for sensitive or itchy skin.',
    shortDescription: 'Soothing oatmeal shampoo',
    price: 14.99,
    category: 'Grooming',
    subcategory: 'Shampoos',
    tags: ['shampoo', 'oatmeal', 'sensitive-skin', 'gentle'],
    images: [petImages.products[1]],
    variants: [
      { id: 'v34-1', name: '16 oz', price: 14.99, stock: 80 },
      { id: 'v34-2', name: '32 oz', price: 24.99, stock: 45 },
    ],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 423,
    stock: 125,
    sku: 'GR-002',
    brand: 'PetSpa',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'all',
    createdAt: '2023-06-20',
  },
  {
    id: '35',
    name: 'Nail Clippers Pro',
    slug: 'nail-clippers-pro',
    description: 'Sharp stainless steel blades with safety guard and ergonomic grip.',
    shortDescription: 'Professional nail clippers',
    price: 12.99,
    category: 'Grooming',
    subcategory: 'Nail Care',
    tags: ['nail', 'clippers', 'safety-guard'],
    images: [petImages.products[0]],
    variants: [
      { id: 'v35-1', name: 'Small Pets', price: 9.99, stock: 55, size: 'S' },
      { id: 'v35-2', name: 'Medium/Large Dogs', price: 12.99, stock: 60, size: 'M' },
    ],
    reviews: generateReviews(4),
    rating: 4.5,
    reviewCount: 312,
    stock: 115,
    sku: 'GR-003',
    brand: 'ClipRight',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'all',
    createdAt: '2023-05-10',
  },
  // Health & Wellness (36-42)
  {
    id: '36',
    name: 'Hip & Joint Supplement',
    slug: 'hip-joint-supplement',
    description: 'Soft chews with glucosamine, chondroitin, and MSM for mobility support.',
    shortDescription: 'Joint health soft chews',
    price: 34.99,
    compareAtPrice: 44.99,
    category: 'Health & Wellness',
    subcategory: 'Supplements',
    tags: ['joint', 'glucosamine', 'mobility', 'supplement'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v36-1', name: '60 Chews', price: 34.99, stock: 45 },
      { id: 'v36-2', name: '120 Chews', price: 59.99, stock: 30 },
    ],
    reviews: generateReviews(6),
    rating: 4.8,
    reviewCount: 445,
    stock: 75,
    sku: 'HW-001',
    brand: 'VitaPaws',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'dog',
    createdAt: '2023-08-25',
  },
  {
    id: '37',
    name: 'Calming Treats',
    slug: 'calming-treats',
    description: 'Natural calming formula with chamomile and L-theanine for anxiety relief.',
    shortDescription: 'Anxiety-relief treats',
    price: 24.99,
    category: 'Health & Wellness',
    subcategory: 'Calming',
    tags: ['calming', 'anxiety', 'natural', 'treats'],
    images: [petImages.products[1]],
    variants: [
      { id: 'v37-1', name: 'Dogs', price: 24.99, stock: 55, size: 'Dog' },
      { id: 'v37-2', name: 'Cats', price: 22.99, stock: 40, size: 'Cat' },
    ],
    reviews: generateReviews(5),
    rating: 4.6,
    reviewCount: 378,
    stock: 95,
    sku: 'HW-002',
    brand: 'ZenPets',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'all',
    createdAt: '2024-02-08',
  },
  {
    id: '38',
    name: 'Dental Chews Multi-Pack',
    slug: 'dental-chews-multi-pack',
    description: 'Daily dental treats that reduce tartar and freshen breath.',
    shortDescription: 'Tartar-control dental treats',
    price: 19.99,
    category: 'Health & Wellness',
    subcategory: 'Dental',
    tags: ['dental', 'tartar', 'fresh-breath', 'chews'],
    images: [petImages.products[0]],
    variants: [
      { id: 'v38-1', name: 'Small Dogs (25 ct)', price: 19.99, stock: 50, size: 'S' },
      { id: 'v38-2', name: 'Medium Dogs (20 ct)', price: 19.99, stock: 45, size: 'M' },
      { id: 'v38-3', name: 'Large Dogs (15 ct)', price: 19.99, stock: 40, size: 'L' },
    ],
    reviews: generateReviews(7),
    rating: 4.7,
    reviewCount: 534,
    stock: 135,
    sku: 'HW-003',
    brand: 'DentaFresh',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2023-09-10',
  },
  // Training & Behavior (39-42)
  {
    id: '39',
    name: 'Training Treat Pouch',
    slug: 'training-treat-pouch',
    description: 'Hands-free pouch with magnetic closure and waste bag dispenser.',
    shortDescription: 'Convenient training pouch',
    price: 16.99,
    category: 'Training',
    subcategory: 'Accessories',
    tags: ['training', 'pouch', 'treats', 'hands-free'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v39-1', name: 'Black', price: 16.99, stock: 60, color: 'Black' },
      { id: 'v39-2', name: 'Blue', price: 16.99, stock: 45, color: 'Blue' },
      { id: 'v39-3', name: 'Gray', price: 16.99, stock: 50, color: 'Gray' },
    ],
    reviews: generateReviews(4),
    rating: 4.6,
    reviewCount: 267,
    stock: 155,
    sku: 'TR-001',
    brand: 'TrainRight',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2023-07-05',
  },
  {
    id: '40',
    name: 'Clicker Training Kit',
    slug: 'clicker-training-kit',
    description: 'Complete kit with 2 clickers, training guide, and treat bag.',
    shortDescription: 'Beginner clicker training set',
    price: 14.99,
    category: 'Training',
    subcategory: 'Clickers',
    tags: ['clicker', 'training', 'kit', 'beginner'],
    images: [petImages.products[1]],
    variants: [],
    reviews: generateReviews(5),
    rating: 4.5,
    reviewCount: 189,
    stock: 80,
    sku: 'TR-002',
    brand: 'TrainRight',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'all',
    createdAt: '2024-01-28',
  },
  // Travel & Outdoor (41-45)
  {
    id: '41',
    name: 'Portable Water Bottle',
    slug: 'portable-water-bottle',
    description: 'Leak-proof bottle with built-in bowl for on-the-go hydration.',
    shortDescription: 'Travel water bottle with bowl',
    price: 18.99,
    category: 'Travel',
    subcategory: 'Water',
    tags: ['travel', 'water-bottle', 'portable', 'leak-proof'],
    images: [petImages.products[0]],
    variants: [
      { id: 'v41-1', name: '12 oz', price: 14.99, stock: 70, size: 'S' },
      { id: 'v41-2', name: '20 oz', price: 18.99, stock: 55, size: 'M' },
      { id: 'v41-3', name: '32 oz', price: 22.99, stock: 40, size: 'L' },
    ],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 345,
    stock: 165,
    sku: 'TV-001',
    brand: 'WalkMate',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'all',
    createdAt: '2023-06-25',
  },
  {
    id: '42',
    name: 'Collapsible Travel Crate',
    slug: 'collapsible-travel-crate',
    description: 'Lightweight, foldable crate for travel and home use.',
    shortDescription: 'Portable folding crate',
    price: 59.99,
    compareAtPrice: 79.99,
    category: 'Travel',
    subcategory: 'Crates',
    tags: ['crate', 'collapsible', 'travel', 'portable'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v42-1', name: 'Small', price: 49.99, stock: 25, size: 'S' },
      { id: 'v42-2', name: 'Medium', price: 59.99, stock: 30, size: 'M' },
      { id: 'v42-3', name: 'Large', price: 79.99, stock: 20, size: 'L' },
    ],
    reviews: generateReviews(4),
    rating: 4.6,
    reviewCount: 223,
    stock: 75,
    sku: 'TV-002',
    brand: 'TravelPaws',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: true,
    petType: 'all',
    createdAt: '2023-10-15',
  },
  {
    id: '43',
    name: 'Car Seat Cover',
    slug: 'car-seat-cover',
    description: 'Waterproof seat protector with side flaps and non-slip backing.',
    shortDescription: 'Waterproof car seat protector',
    price: 39.99,
    category: 'Travel',
    subcategory: 'Car Accessories',
    tags: ['car', 'seat-cover', 'waterproof', 'protection'],
    images: [petImages.products[1]],
    variants: [],
    reviews: generateReviews(5),
    rating: 4.7,
    reviewCount: 289,
    stock: 45,
    sku: 'TV-003',
    brand: 'TravelPaws',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'all',
    createdAt: '2023-09-20',
  },
  // Treats & Chews (44-50)
  {
    id: '44',
    name: 'Natural Bully Sticks',
    slug: 'natural-bully-sticks',
    description: 'Single-ingredient, grass-fed beef bully sticks. Fully digestible.',
    shortDescription: 'Premium beef bully sticks',
    price: 29.99,
    compareAtPrice: 39.99,
    category: 'Treats',
    subcategory: 'Chews',
    tags: ['bully-stick', 'natural', 'beef', 'single-ingredient'],
    images: [petImages.products[0]],
    variants: [
      { id: 'v44-1', name: '6-inch (5 pack)', price: 19.99, stock: 50 },
      { id: 'v44-2', name: '12-inch (5 pack)', price: 29.99, stock: 40 },
    ],
    reviews: generateReviews(7),
    rating: 4.8,
    reviewCount: 678,
    stock: 90,
    sku: 'TC-001',
    brand: 'NaturalPaws',
    isFeatured: true,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: true,
    petType: 'dog',
    createdAt: '2023-08-10',
  },
  {
    id: '45',
    name: 'Training Treats Chicken',
    slug: 'training-treats-chicken',
    description: 'Small, soft treats perfect for training. Made with real chicken.',
    shortDescription: 'Bite-sized training treats',
    price: 9.99,
    category: 'Treats',
    subcategory: 'Training Treats',
    tags: ['training', 'chicken', 'soft', 'small'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v45-1', name: '6 oz', price: 9.99, stock: 100 },
      { id: 'v45-2', name: '16 oz', price: 19.99, stock: 60 },
    ],
    reviews: generateReviews(5),
    rating: 4.6,
    reviewCount: 456,
    stock: 160,
    sku: 'TC-002',
    brand: 'TreatTime',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2023-07-20',
  },
  {
    id: '46',
    name: 'Freeze-Dried Salmon Treats',
    slug: 'freeze-dried-salmon-treats',
    description: 'Single ingredient freeze-dried wild salmon. High protein, no additives.',
    shortDescription: 'Pure salmon treats',
    price: 16.99,
    category: 'Treats',
    subcategory: 'Freeze-Dried',
    tags: ['freeze-dried', 'salmon', 'single-ingredient', 'high-protein'],
    images: [petImages.products[1]],
    variants: [
      { id: 'v46-1', name: 'Dogs', price: 16.99, stock: 55 },
      { id: 'v46-2', name: 'Cats', price: 14.99, stock: 50 },
    ],
    reviews: generateReviews(5),
    rating: 4.9,
    reviewCount: 345,
    stock: 105,
    sku: 'TC-003',
    brand: 'PureRewards',
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: false,
    petType: 'all',
    createdAt: '2024-02-12',
  },
  {
    id: '47',
    name: 'Dental Sticks Value Pack',
    slug: 'dental-sticks-value-pack',
    description: 'Daily dental care sticks with mint flavor for fresh breath.',
    shortDescription: 'Fresh breath dental sticks',
    price: 24.99,
    category: 'Treats',
    subcategory: 'Dental',
    tags: ['dental', 'mint', 'fresh-breath', 'value-pack'],
    images: [petImages.products[0]],
    variants: [
      { id: 'v47-1', name: '28 Count', price: 24.99, stock: 65 },
      { id: 'v47-2', name: '56 Count', price: 44.99, stock: 35 },
    ],
    reviews: generateReviews(4),
    rating: 4.5,
    reviewCount: 234,
    stock: 100,
    sku: 'TC-004',
    brand: 'DentaFresh',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: false,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2023-11-25',
  },
  {
    id: '48',
    name: 'Crunchy Cat Treats Tuna',
    slug: 'crunchy-cat-treats-tuna',
    description: 'Crunchy treats made with real tuna. Irresistible to cats.',
    shortDescription: 'Tuna flavor crunchy treats',
    price: 7.99,
    category: 'Treats',
    subcategory: 'Cat Treats',
    tags: ['cat', 'tuna', 'crunchy', 'fish'],
    images: [petImages.products[2]],
    variants: [
      { id: 'v48-1', name: '2.5 oz', price: 7.99, stock: 90 },
      { id: 'v48-2', name: '6 oz', price: 14.99, stock: 55 },
    ],
    reviews: generateReviews(6),
    rating: 4.7,
    reviewCount: 423,
    stock: 145,
    sku: 'TC-005',
    brand: 'Whisker Delights',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'cat',
    createdAt: '2023-10-05',
  },
  {
    id: '49',
    name: 'Jerky Strips Variety',
    slug: 'jerky-strips-variety',
    description: 'Variety pack with chicken, beef, and duck jerky strips.',
    shortDescription: 'Mixed protein jerky treats',
    price: 19.99,
    compareAtPrice: 26.99,
    category: 'Treats',
    subcategory: 'Jerky',
    tags: ['jerky', 'variety', 'protein', 'meaty'],
    images: [petImages.products[1]],
    variants: [],
    reviews: generateReviews(5),
    rating: 4.6,
    reviewCount: 312,
    stock: 70,
    sku: 'TC-006',
    brand: 'MeatyBites',
    isFeatured: false,
    isNewArrival: true,
    isBestSeller: false,
    isOnSale: true,
    petType: 'dog',
    createdAt: '2024-01-18',
  },
  {
    id: '50',
    name: 'Peanut Butter Biscuits',
    slug: 'peanut-butter-biscuits',
    description: 'Crunchy biscuits made with natural peanut butter. No artificial flavors.',
    shortDescription: 'Natural PB dog biscuits',
    price: 11.99,
    category: 'Treats',
    subcategory: 'Biscuits',
    tags: ['peanut-butter', 'biscuit', 'crunchy', 'natural'],
    images: [petImages.products[0]],
    variants: [
      { id: 'v50-1', name: '16 oz', price: 11.99, stock: 75 },
      { id: 'v50-2', name: '32 oz', price: 19.99, stock: 45 },
    ],
    reviews: generateReviews(6),
    rating: 4.8,
    reviewCount: 534,
    stock: 120,
    sku: 'TC-007',
    brand: 'TreatTime',
    isFeatured: false,
    isNewArrival: false,
    isBestSeller: true,
    isOnSale: false,
    petType: 'dog',
    createdAt: '2023-12-01',
  },
]

// Hero Slides
export const heroSlides: HeroSlide[] = [
  {
    id: '1',
    title: 'Love Your Pets More',
    subtitle: 'Premium Pet Products',
    description: 'Discover our curated collection of premium pet supplies designed with love for your furry friends.',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1920',
    ctaText: 'Shop Now',
    ctaLink: '/shop',
    secondaryCtaText: 'View Collections',
    secondaryCtaLink: '/collections',
    textPosition: 'left',
  },
  {
    id: '2',
    title: 'New Arrivals',
    subtitle: 'Fresh Collection 2024',
    description: 'Check out our latest products for your beloved pets. Quality you can trust.',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=1920',
    ctaText: 'Explore New',
    ctaLink: '/shop?filter=new',
    textPosition: 'center',
  },
  {
    id: '3',
    title: 'Up to 40% Off',
    subtitle: 'Winter Sale',
    description: 'Limited time offer on selected items. Dont miss out on these amazing deals!',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=1920',
    ctaText: 'Shop Sale',
    ctaLink: '/shop?filter=sale',
    textPosition: 'right',
  },
  {
    id: '4',
    title: 'Premium Dog Food',
    subtitle: 'Nutrition First',
    description: 'Give your pets the nutrition they deserve with our premium grain-free formulas.',
    image: 'https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=1920',
    ctaText: 'Shop Food',
    ctaLink: '/shop?category=food',
    textPosition: 'left',
  },
  {
    id: '5',
    title: 'Cozy Comfort',
    subtitle: 'Beds & Furniture',
    description: 'Let your pets rest in style with our comfortable beds and furniture.',
    image: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=1920',
    ctaText: 'Shop Beds',
    ctaLink: '/shop?category=beds',
    textPosition: 'center',
  },
]

// Testimonials (Indian Customers)
export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    location: 'Mumbai, Maharashtra',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    petImage: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400',
    petName: 'Bruno',
    rating: 5,
    content: 'BowPaw has the best quality pet products in India! My dog Bruno absolutely loves his new orthopedic bed. Delivery was super fast!',
  },
  {
    id: '2',
    name: 'Rahul Patel',
    location: 'Bangalore, Karnataka',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    petImage: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400',
    petName: 'Mitthu',
    rating: 5,
    content: 'The cat tree I ordered exceeded my expectations. Mitthu spends all day on it. Best pet store in Bangalore!',
  },
  {
    id: '3',
    name: 'Ananya Reddy',
    location: 'Hyderabad, Telangana',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
    petImage: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400',
    petName: 'Tommy',
    rating: 5,
    content: 'Amazing customer service and the products are top-notch. Tommy loves his new toys and treats! Will recommend to all pet parents.',
  },
  {
    id: '4',
    name: 'Vikram Singh',
    location: 'Delhi, NCR',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
    petImage: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=400',
    petName: 'Sheru',
    rating: 4,
    content: 'Great selection of premium cat food. Sheru is healthier and happier since we switched to BowPaw products. Prices are very reasonable!',
  },
  {
    id: '5',
    name: 'Kavya Nair',
    location: 'Chennai, Tamil Nadu',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200',
    petImage: 'https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=400',
    petName: 'Rocky',
    rating: 5,
    content: 'The subscription service is so convenient! Rocky never runs out of his favorite food now. Best pet shop in Chennai!',
  },
]

// Blog Posts (Indian Authors)
export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: '10 Essential Tips for New Puppy Parents in India',
    slug: '10-essential-tips-new-puppy-parents',
    excerpt: 'Bringing home a new puppy is exciting! Here are our top tips to help you and your furry friend start off on the right paw.',
    content: 'Full article content about puppy care...',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
    author: 'Dr. Meera Krishnan',
    authorImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    category: 'Dog Care',
    tags: ['puppies', 'training', 'new-pet', 'tips'],
    publishedAt: '2024-02-15',
    readTime: 8,
  },
  {
    id: '2',
    title: 'Understanding Your Cats Body Language',
    slug: 'understanding-cat-body-language',
    excerpt: 'Learn to decode what your cat is really telling you through their tail movements, ear positions, and vocalizations.',
    content: 'Full article content about cat body language...',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800',
    author: 'Dr. Anjali Desai',
    authorImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    category: 'Cat Care',
    tags: ['cats', 'behavior', 'communication'],
    publishedAt: '2024-02-10',
    readTime: 6,
  },
  {
    id: '3',
    title: 'The Best Diet for Senior Dogs in Indian Climate',
    slug: 'best-diet-senior-dogs',
    excerpt: 'As dogs age, their nutritional needs change. Discover the best foods and supplements to keep your senior dog healthy.',
    content: 'Full article content about senior dog nutrition...',
    image: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800',
    author: 'Dr. Rajesh Gupta',
    authorImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    category: 'Nutrition',
    tags: ['senior-dogs', 'nutrition', 'health', 'diet'],
    publishedAt: '2024-02-05',
    readTime: 10,
  },
  {
    id: '4',
    title: 'How to Create a Cat-Friendly Indian Home',
    slug: 'create-cat-friendly-home',
    excerpt: 'Transform your living space into a feline paradise with these simple modifications and additions.',
    content: 'Full article content about cat-friendly homes...',
    image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=800',
    author: 'Sneha Iyer',
    authorImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
    category: 'Cat Care',
    tags: ['cats', 'home', 'environment', 'enrichment'],
    publishedAt: '2024-01-28',
    readTime: 7,
  },
  {
    id: '5',
    title: 'Summer Safety Tips for Pets in India',
    slug: 'summer-safety-tips-pets',
    excerpt: 'Keep your pets safe and cool during the hot Indian summer months with these essential tips.',
    content: 'Full article content about summer pet safety...',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800',
    author: 'Dr. Meera Krishnan',
    authorImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    category: 'Health',
    tags: ['summer', 'safety', 'heat', 'outdoor'],
    publishedAt: '2024-01-20',
    readTime: 5,
  },
  {
    id: '6',
    title: 'Choosing the Right Toy for Your Dog',
    slug: 'choosing-right-toy-dog',
    excerpt: 'Not all toys are created equal. Learn how to pick the perfect toys based on your dogs size, age, and play style.',
    content: 'Full article content about dog toys...',
    image: 'https://images.unsplash.com/photo-1598133894008-61f7fdb8cc3a?w=800',
    author: 'Arjun Mehta',
    authorImage: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100',
    category: 'Dog Care',
    tags: ['toys', 'play', 'enrichment', 'safety'],
    publishedAt: '2024-01-15',
    readTime: 6,
  },
  {
    id: '7',
    title: 'Introduction to Clicker Training',
    slug: 'introduction-clicker-training',
    excerpt: 'Clicker training is an effective and fun way to teach your pet new behaviors. Heres how to get started.',
    content: 'Full article content about clicker training...',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800',
    author: 'Pooja Bhatt',
    authorImage: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    category: 'Training',
    tags: ['training', 'clicker', 'behavior', 'positive-reinforcement'],
    publishedAt: '2024-01-10',
    readTime: 8,
  },
  {
    id: '8',
    title: 'Natural Remedies for Pet Anxiety',
    slug: 'natural-remedies-pet-anxiety',
    excerpt: 'Help your anxious pet find calm with these natural Ayurvedic approaches and remedies.',
    content: 'Full article content about pet anxiety...',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800',
    author: 'Dr. Anjali Desai',
    authorImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    category: 'Health',
    tags: ['anxiety', 'natural', 'calming', 'wellness'],
    publishedAt: '2024-01-05',
    readTime: 7,
  },
]

// Collections
export const collections: Collection[] = [
  { id: '1', name: 'Dog Food', slug: 'dog-food', description: 'Premium nutrition for your canine companion', image: petImages.dogs[0], productCount: 15 },
  { id: '2', name: 'Cat Food', slug: 'cat-food', description: 'Delicious and nutritious meals for cats', image: petImages.cats[0], productCount: 12 },
  { id: '3', name: 'Dog Toys', slug: 'dog-toys', description: 'Fun toys to keep your dog entertained', image: petImages.dogs[1], productCount: 18 },
  { id: '4', name: 'Cat Toys', slug: 'cat-toys', description: 'Interactive toys for playful cats', image: petImages.cats[1], productCount: 14 },
  { id: '5', name: 'Beds & Furniture', slug: 'beds-furniture', description: 'Comfortable resting spots for pets', image: petImages.dogs[2], productCount: 10 },
  { id: '6', name: 'Health & Wellness', slug: 'health-wellness', description: 'Keep your pets healthy and happy', image: petImages.dogs[3], productCount: 8 },
]

// FAQs
export const faqs: FAQItem[] = [
  { id: '1', question: 'How long does shipping take?', answer: 'Standard shipping takes 3-5 business days. Express shipping is available for 1-2 day delivery.', category: 'Shipping' },
  { id: '2', question: 'What is your return policy?', answer: 'We offer 30-day hassle-free returns on all unused items in original packaging.', category: 'Returns' },
  { id: '3', question: 'Do you offer international shipping?', answer: 'Yes! We ship to over 50 countries. International shipping typically takes 7-14 business days.', category: 'Shipping' },
  { id: '4', question: 'Are your products safe for puppies/kittens?', answer: 'Each product has age recommendations. Look for the life stage indicator on product pages.', category: 'Products' },
  { id: '5', question: 'How can I track my order?', answer: 'Once shipped, youll receive a tracking number via email to monitor your delivery.', category: 'Orders' },
  { id: '6', question: 'Do you have a loyalty program?', answer: 'Yes! Earn PawPoints on every purchase and redeem them for discounts on future orders.', category: 'Rewards' },
]

// Stats (Indian Context)
export const stats: Stat[] = [
  { id: '1', label: 'Happy Pets in India', value: 100000, suffix: '+', icon: 'heart' },
  { id: '2', label: 'Products', value: 2500, suffix: '+', icon: 'package' },
  { id: '3', label: '5-Star Reviews', value: 25000, suffix: '+', icon: 'star' },
  { id: '4', label: 'Cities We Deliver', value: 500, suffix: '+', icon: 'globe' },
]

// Helper functions
export const getProductById = (id: string): Product | undefined => products.find(p => p.id === id)
export const getProductBySlug = (slug: string): Product | undefined => products.find(p => p.slug === slug)
export const getFeaturedProducts = (): Product[] => products.filter(p => p.isFeatured)
export const getBestSellers = (): Product[] => products.filter(p => p.isBestSeller)
export const getNewArrivals = (): Product[] => products.filter(p => p.isNewArrival)
export const getOnSaleProducts = (): Product[] => products.filter(p => p.isOnSale)
export const getProductsByCategory = (category: string): Product[] => products.filter(p => p.category === category)
export const getProductsByPetType = (petType: string): Product[] => products.filter(p => p.petType === petType || p.petType === 'all')
export const searchProducts = (query: string): Product[] => {
  const lowerQuery = query.toLowerCase()
  return products.filter(p =>
    p.name.toLowerCase().includes(lowerQuery) ||
    p.description.toLowerCase().includes(lowerQuery) ||
    p.tags.some(t => t.toLowerCase().includes(lowerQuery))
  )
}

